branches:
  only:
  - master
language: java
env:
  - BUILD_DIR=Vjezbe02/Zadatak1
  - BUILD_DIR=Vjezbe02/Zadatak2
  - BUILD_DIR=Vjezbe02/Zadatak3
  - BUILD_DIR=Vjezbe03/Zadatak4
  - BUILD_DIR=Vjezbe05/Zadatak5
script: cd $BUILD_DIR && mvn test