MERGE INTO LIBRARY.AUTHOR (FIRST_NAME, LAST_NAME) KEY (FIRST_NAME, LAST_NAME) VALUES ('Franz', 'Kafka');
MERGE INTO LIBRARY.BOOK (ID, TITLE, AUTHOR_ID) KEY (ID) VALUES (SELECT TOP(1) ID FROM LIBRARY.BOOK WHERE TITLE = 'The Metamorphosis', 'The Metamorphosis', SELECT ID FROM LIBRARY.AUTHOR WHERE FIRST_NAME = 'Franz' AND LAST_NAME = 'Kafka');
MERGE INTO LIBRARY.LIBRARIAN (USERNAME, FIRST_NAME, LAST_NAME) KEY (USERNAME) VALUES ('rgiles', 'Rupert', 'Giles');
MERGE INTO LIBRARY.PERSON (FIRST_NAME, LAST_NAME) KEY (FIRST_NAME, LAST_NAME) VALUES ('John', 'Doe');
